### ISSUE TITLE
Add option to set video alignment for mobile vertical

### ISSUE THREAD

**Issue by muraldouglas** [GetMural/Mural#11]
Mural currently aligns videos to the left of the viewport, which is fine when the reader is viewing a story on a desktop machine or on a mobile phone holding the phone horizontally. On Mural's video items (background video and fullpage video) we should add the option for the Mural user to set the alignment of the video if the reader views the story in vertical mode; the user should be able to set the alignment to left, center or right.

**Comment by Flowdeeps** [comment]
Fixed in 0.2.8
