### ISSUE TITLE
Suggestion: Add Auto-updating fields to Templates

### ISSUE THREAD

**Issue by GeorgeWL** [GetMural/Mural#170]
A common use-case is we create a new retro board each week, from the same template, and have to manually update the date each time

A nice-to-have would be the option to add a "Smart Field" that automatically updates when template is cloned, for example to set the text as Todays Date

**Comment by PeteHaughie** [comment]
Hi George. I think you might be confusing Murals here. GetMural is an open source tool for composing longform visual stories with HTML, CSS, and JS and Mural is a proprietary and closed source online whiteboarding and collaboration tool.

**Comment by GeorgeWL** [comment]
I for sure am, thanks, I'll close this then 🙂
