### ISSUE TITLE
Add support for Twitter cards

### ISSUE THREAD

**Issue by muraldouglas** [GetMural/Mural#42]
In addition to the Open Graph Protocol support we have so that stories look good when shared on Facebook, we should add support for Twitter Cards (https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started). While these can be added after the story is downloaded, it's kind of a pain and doing it by hand always raises the possibility that things will go wrong.

`<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@nytimesbits" />
<meta name="twitter:creator" content="@nickbilton" />
<meta property="og:url" content="http://bits.blogs.nytimes.com/2011/12/08/a-twitter-for-my-sister/" />
<meta property="og:title" content="A Twitter for My Sister" />
<meta property="og:description" content="In the early days, Twitter grew so quickly that it was almost impossible to add new features because engineers spent their time trying to keep the rocket ship from stalling." />
<meta property="og:image" content="http://graphics8.nytimes.com/images/2011/12/08/technology/bits-newtwitter/bits-newtwitter-tmagArticle.jpg" />
`

**Comment by naomiaro** [comment]
Done in the new betas
