### ISSUE TITLE
Mp4 not playing in safari

### ISSUE THREAD

**Issue by DominicSmith** [GetMural/Mural#50]
See story - http://stories.d6culture.org/nicolasingh/stickyweeds/  

Plays in Chrome and Firefox, but displays static image in Safari. May relate to issue with cloudflare -https://community.cloudflare.com/t/mp4-videos-not-working-on-safari/50818 or another issue with the hosts server which I am investigating.

**Comment by naomiaro** [comment]
@DominicSmith did you have any luck with this?

**Comment by DominicSmith** [comment]
I think it had something to do with apple whitelisting/blacklisting sites it allows autostart on.

**Comment by naomiaro** [comment]
I think this should be fixed in the new betas.
