### ISSUE TITLE
Incorrect Debian binary package

### ISSUE THREAD

**Issue by abhas** [GetMural/Mural#52]
The `Mural-0.3.0-amd64.deb.zip` file doesn't seem to contain a `.deb` file or what might appear to be a binary pre-compiled package for GNU/Linux.

**Comment by naomiaro** [comment]
https://www.getmural.io/

Do the current ones work OK for you? Now they have been built on an actual machine.

**Comment by abhas** [comment]
Nope. The Debian package (`Mural-0.3.0-amd64.deb.zip`) still does not contain a `.deb` package after I unzip it. It contains a `Mural.app` directory which seems to have the macos application. Not the Debian binaries.

**Comment by muraldouglas** [comment]
Please try it now. I've updated the link on our site.

**Comment by abhas** [comment]
Yes - the package works perfectly now. Thanks a lot.

I also noticed that there is no significant size difference between the `.zip` and the `.deb`. This is because the `.deb` package is already compressed and so there is nothing to gain by compressing it again. You might as well share the `.deb` directly without zipping it first.

**Comment by naomiaro** [comment]
Great! That's a good point about the debs, will see next time we create packages what to do.
