### ISSUE TITLE
ensure only one video playing at any given moment

### ISSUE THREAD

**Issue by dpocock** [GetMural/Mural#67]
In one project, I have a video panning left-to-right and the next video pans right-to-left

As the user is navigating from the first video to the second video, they see bits of both videos moving.  One user expressed concern about the effect.

Is it possible to ensure that only one of the videos is playing?

Even better, could some more advanced transition be used to fade from one to the other, instead of ordinary scrolling?

As a workaround, I could insert a static slide between the two videos or try to avoid using two videos like this together.

**Comment by naomiaro** [comment]
new betas should only have one video playing.
