### ISSUE TITLE
move more details from manual to UI

### ISSUE THREAD

**Issue by dpocock** [GetMural/Mural#68]
There are many cases where a user needs to refer to the manual

Example: the small, medium and large image sizes.  Could the recommended dimensions be included in the UI or easily accessible with a help button?

The manual explains a lot of things that could be clarified in the UI.  Example from page 35:

"The difference between a background video and a full-page video is that a
background video can have text overlaid over it"

The UI titles for the two types of video could be elaborated slightly in the item chooser menu:
"background video, text overlay and looping"
"full page video, title text only and auto-advance"

For users who only use Mural occasionally, this type of hinting can help jog their memory.

**Comment by naomiaro** [comment]
new website includes item screenshots and manual info.
